# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 77feb95711a8bff6cc5bacb347192b87f6f59a57c37722d02001869eaa173f6c8f6fad6f79bdd15a3581e762c2e3528bee44085e1877a0fc11f0edab4ef415ea

test:
  secret_key_base: eef577c56701534c4f34f59e32e09cb9f47934eb9eac63b1b2b042a982cbe4e2a7ca0b82f33b5847efe77c7e6bf20136c94632d1fc26518522c0f053c1ef8517

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
